### ISSUE TITLE
Doubts about usage

### ISSUE THREAD

**Issue by lazywithclass** [paysdoc/js-mutation-testing#2]
Hello, first of all thanks for your work!

I am trying to see if I could use this library for a service I'm writing, I'm reading the source and playing a bit with it. I've started with a simple example, I was expecting a failure but I didn't get one, I'm sure I am doing something silly with the config though.

In this example I am defining a function called `sum` but I've used `-` in the implementation, so since applying the mutation doesn't change the positive outcome of the tests, there should be a report about a problem (I am right with this assumption?).

``` javascript
var MutationTester = require('./src/MutationTester'),
    Mocha = require('mocha');


new MutationTester({
  lib: [],
  mutate: 'to-be-mutated.js',
  specs: 'to-be-mutated-spec.js',
  basePath: process.cwd(),
  logLevel: 'TRACE'
}).test(function(config, cb) {

  var mocha = new Mocha({});
  mocha.addFile('./to-be-mutated-test');
  mocha.run();
});
```

This is the file to be tested

``` javascript
var lib = {};

lib.sum = function(a, b) {
  return a - b;
};

module.exports = lib;
```

This is the spec

``` javascript
describe('testing', function() {

  var lib = require('./to-be-mutated'),
      expect = require('chai').expect;

  it('sums', function() {
    expect(lib.sum(2, 0)).to.equal(2);
  });

});
```

I see in the output that the `BLOCK_STATEMENT` mutation has been chosen and applied, what's not clear is why wasn't `MATH` applied?

Also, is it the same to invoke `test` on `MutationTester` or pass a `test` attribute to `new MutationTester`?

Many thanks in advance

**Comment by paysdoc** [comment]
Hi, 
Thanks for trying out this module. Unfortunately I'm still busy working on and testing it whenever I have time and I don't think it's quite ready yet for your needs. So the problems you're running into are more likely in my code than yours at this stage. 

I could incorporate your tests into my e2e tests and see what's going wrong (there's a whole list of silly little tests that should survive when they're not supposed to, but so far I'm trying to get one to work and then continue from there). 

As for instaniation: MutationTester should indeed be called with 'new', otherwise it won't do what you expect it to - well it doesn't anyway, but... you know what I mean. :p 

If you do want to try out mutation testing - and you happen to be running Grunt, you could give [grunt-mutation-testing](https://github.com/jimivdw/grunt-mutation-testing) a go. Jimmy and I have been working on it last year and it should be reasonably stable. 

This project is a spin-off to just get a pure JS core that can then work with different builders and testing frameworks. Once I've finished my Swift assignment at the end of this week I'll continue working on this.

**Comment by lazywithclass** [comment]
Ok I see, thanks for the explanation :)
